version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/k8stool
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X k8stool/cmd/k8stool.version={{.Version}} -X k8stool/cmd/k8stool.commit={{.Commit}} -X k8stool/cmd/k8stool.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: eniayomi
      name: homebrew-tap
      branch: main
    homepage: "https://github.com/eniayomi/k8stool"
    description: "A command-line tool for managing Kubernetes resources"
    commit_author:
      name: eniayomi
      email: oluwaseyieniayomi@gmail.com
    install: |
      bin.install "k8stool"
    test: |
      system "#{bin}/k8stool version"
